[project]
name = "audio-project"
version = "0.1.0"
description = "Speech Emotion Recognition with CNN-LSTM and Wav2Vec2"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "accelerate>=0.30",
  "fastapi>=0.111",
  "gradio>=4.36",
  "huggingface-hub>=0.24",
  "jupyter>=1.1.1",
  "librosa>=0.11.0",
  "matplotlib>=3.10.6",
  "mlflow>=2.14",
  "notebook>=7.4.5",
  "numpy>=2.2.6",
  "pandas>=2.3.2",
  "pandas-stubs>=2.3.2.250827",
  "pillow>=12.1.1",
  "pytorch-lightning>=2.6.1",
  "scikit-learn>=1.5",
  "seaborn>=0.13.2",
  "setuptools>=75.0.0,<76",
  "sounddevice>=0.5",
  "soundfile>=0.13.1",
  "tensorboard>=2.20.0",
  "torch>=2.8.0",
  "torchaudio>=2.8.0",
  "torchvision>=0.23.0",
  "tqdm>=4.67.1",
  "transformers>=4.44",
  "uvicorn>=0.30",
]

